set(APP_NAME ws2812-clock)

add_definitions(
    -fdiagnostics-color=always

    # I2C Config / sensors
    -DHARDWARE_USE_BME280
    # -DHARDWARE_USE_SHT30
    -DHARDWARE_I2C_SDA=25
    -DHARDWARE_I2C_SCL=26

    -DHARDWARE_BARREL_JACK_PIN=4

    # LED Config
    -DHARDWARE_WS2812B_COUNT=232
    -DHARDWARE_WS2812B_PIN=32
    -DHARDWARE_WS2812B_COLOR_ORDER=GRB
    -DHARDWARE_AP_STATUS_LED_PIN=GPIO_NUM_15
    -DHARDWARE_STA_STATUS_LED_PIN=GPIO_NUM_16
    -DHARDWARE_ALARM_STATUS_LED_PIN=GPIO_NUM_17

    # Beeper Config
    -DHARDWARE_BEEPER_PIN=13

    # Buttons
    -DHARDWARE_BUTTON_TOGGLE_AP=21
    -DHARDWARE_BUTTON_TOGGLE_ALARM=22
    -DHARDWARE_BUTTON_SNOOZE_ALARM=23

)
